### ISSUE TITLE
Help Needed - Feature requests!

### ISSUE THREAD

**Issue by cjavad** [cjavad/hashit#1]
So i am pretty much empty of all ideas concerning this project, so i am turning to you, my dear "users" for help, all feedback Will be appriciated. 

*Note*:  I will be continuing to release bugfixes, but for now, no new features 😞. Unless you want some of course!

**Comment by JavadSM** [comment]
I am personly thinking to add --dry-run to list all the files that will be used/written to and maybe better integration for the shake-hash

**Comment by JavadSM** [comment]
Thinking about making [this](http://www.hashitapp.com/) tool obsolete

**Comment by cjavad** [comment]
Closed as of 2d8eb6fd355e2a33607988985f8ddc0780b6a59f
